[env:STC89C52RC]
platform = intel_mcs51
board = STC89C52RC

upload_protocol = custom
upload_command = uv run main.py

; Windows系统命令示例
;upload_command = .venv\Scripts\python.exe -m stcgal -P auto -p COM3 .pio\build\STC89C52RC\firmware.hex

; Linux系统命令示例
;upload_command = .venv/bin/python -m stcgal -P auto -p /dev/ttyUSB0 .pio/build/STC89C52RC/firmware.hex